name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create package.json
        run: |
          echo '{
            "name": "stratoptimus-docs",
            "version": "1.0.0",
            "scripts": {
              "build": "next build"
            }
          }' > package.json

      - name: Create next.config.js
        run: |
          echo "const withNextra = require('nextra')({
            theme: 'nextra-theme-docs',
            themeConfig: './theme.config.js'
          })
          module.exports = withNextra()" > next.config.js

      - name: Create theme.config.js
        run: |
          echo "export default {
            logo: <span>StratOptimus-TradingWizard</span>,
            project: {
              link: 'https://github.com/jmanhype/stratoptimus-docs'
            }
          }" > theme.config.js

      - name: Install dependencies
        run: npm install nextra next react react-dom

      - name: Build
        run: npx next build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
