name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create package.json
        run: |
          echo '{
            "name": "stratoptimus-docs",
            "version": "1.0.0",
            "type": "module",
            "scripts": {
              "dev": "next dev",
              "build": "next build",
              "start": "next start"
            },
            "dependencies": {
              "next": "latest",
              "nextra": "latest",
              "nextra-theme-docs": "latest",
              "react": "latest",
              "react-dom": "latest"
            }
          }' > package.json

      - name: Create next.config.js
        run: |
          echo "import withNextra from 'nextra'

          export default withNextra({
            theme: 'nextra-theme-docs',
            themeConfig: './theme.config.js',
          })" > next.config.js

      - name: Create theme.config.js
        run: |
          echo "export default {
            logo: '<span>StratOptimus-TradingWizard</span>',
            project: {
              link: 'https://github.com/jmanhype/stratoptimus-docs'
            }
          }" > theme.config.js

      - name: Create pages directory and index.mdx
        run: |
          mkdir -p pages
          echo "# Welcome to StratOptimus-TradingWizard" > pages/index.mdx

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Export static files
        run: npx next export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
